[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

gas_reports = ["*"]
fs_permissions = [{ access = "read", path = "./"}]

fuzz_runs = 256

auto_detect_solc = true